#!/usr/bin/env python
# coding=utf-8

import sys
import subprocess
import AutoVersion
import addpremsg
from CommitMsgStyle import CheckMsgStyle

def main():
    
    addpremsg.add_subject_if_need()

    CheckMsgStyle.check_msg_if_need()

    #添加分支名字到最前边
    #addpremsg.add_premsg_if_need()

    #自动增加版本号
    #AutoVersion.add_version_if_need()

    pass

if __name__ == '__main__':
    
    print "-->git hook脚本commit-msg开始执行"
    main()
    print "-->git hook脚本commit-msg执行完毕\n"
    
    pass


