#!/usr/bin/env python
# coding=utf-8

import sys
from CheckSameImgName import CheckImgName


def main():

	#检查同名图片
	CheckImgName.check_img_if_need()
	
	pass

if __name__ == '__main__':
		
	print "-->git hook脚本prepare-commit-msg开始执行"
	main()
	print "-->git hook脚本prepare-commit-msg执行完毕\n"
	
	pass


